---
title: "importing census data"
author: "Jean Jimenez"
date: "2024-09-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readr)

library(tidycensus)
library(dplyr)
library(purrr)
```

```{r}

api_key <- read_file("census_api_key.txt")


```



```{r}
census_api_key(api_key, install = TRUE)

years <- 2013:2022

variables <- c(
  # Demographics: Race and ethnicity
  total_population = "B02001_001",
  white_alone = "B02001_002",
  black_alone = "B02001_003",
  american_indian_alone = "B02001_004",
  asian_alone = "B02001_005",
  hispanic_latino = "B03002_012",
  
  # Education
  total_population_25_over = "B15003_001",
  bachelors_degree = "B15003_017",
  graduate_professional_degree = "B15003_022",
  
  # Language spoken at home
  total_population_5_over = "B16001_001",
  english_only = "B16001_002",
  spanish = "B16001_003",
  indo_european_languages = "B16001_006",
  asian_pacific_languages = "B16001_009",
  
  # Income
  median_income = "B19013_001"
)


census_data <- map_df(years, function(year) {
  get_acs(
    geography = "zip code tabulation area",  
    variables = variables,                   
    year = year,                             
    survey = "acs5",                         
    output = "wide"                          
  ) %>%
  mutate(year = year)                        
})

 
head(census_data)
```

```{r}
names(census_data)

census_data= census_data %>%
  select(-NAME)

write.csv(census_data, "census_data_2013_2022.csv")
```

